/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package tripplanner.ui;

/**
 *
 * @author Compumarts
 */
public class InputForm extends javax.swing.JDialog {
    private tripplanner.model.ItineraryItem createdItem = null;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InputForm.class.getName());

    /**
     * Creates new form InputForm
     */
    public InputForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Add New Plan");
        setSize(440, 520);
        setLocationRelativeTo(parent);
        setResizable(false);

        // Colors â€” reliable way, done in code
        getContentPane().setBackground(new java.awt.Color(17, 24, 39));
        applyFormColors();

        // Date spinner setup
        dateSpinner.setModel(
            new javax.swing.SpinnerDateModel(new java.util.Date(),
            null, null, java.util.Calendar.DAY_OF_MONTH));
        dateSpinner.setEditor(
            new javax.swing.JSpinner.DateEditor(dateSpinner, "yyyy-MM-dd"));

        // Nights spinner setup
        nightsSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 365, 1));
    }
    private void applyFormColors() {
        java.awt.Color bg    = new java.awt.Color(17,  24,  39);
        java.awt.Color card  = new java.awt.Color(55,  65,  81);
        java.awt.Color text  = new java.awt.Color(243, 244, 246);
        java.awt.Color muted = new java.awt.Color(156, 163, 175);

        // All labels â†’ muted color
        for (java.awt.Component c : getContentPane().getComponents()) {
            if (c instanceof javax.swing.JLabel) {
                c.setForeground(muted);
            }
        }

        // Inputs â†’ dark surface color
        titleField.setBackground(card);
        titleField.setForeground(text);
        titleField.setCaretColor(text);

        costField.setBackground(card);
        costField.setForeground(text);
        costField.setCaretColor(text);

        extraField.setBackground(card);
        extraField.setForeground(text);
        extraField.setCaretColor(text);

        typeComboBox.setBackground(card);
        typeComboBox.setForeground(text);

        dateSpinner.setBackground(card);
        dateSpinner.setForeground(text);

        nightsSpinner.setBackground(card);
        nightsSpinner.setForeground(text);

        // Buttons
        cancelBtn.setBackground(card);
        cancelBtn.setForeground(text);
        cancelBtn.setOpaque(true);

        saveBtn.setBackground(new java.awt.Color(52, 211, 153));
        saveBtn.setForeground(new java.awt.Color(17, 24, 39));
        saveBtn.setOpaque(true);
}

    public tripplanner.model.ItineraryItem getCreatedItem() {
        return createdItem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        dateSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        costField = new javax.swing.JTextField();
        extraField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nightsSpinner = new javax.swing.JSpinner();
        cancelBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("âœˆ  Add New Plan");

        jLabel2.setText("Item Type:");

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Flight", "Hotel", "Activity" }));

        jLabel3.setText("Title:");

        jLabel4.setText("Date:");

        jLabel5.setText("Cost ($):");

        extraField.addActionListener(this::extraFieldActionPerformed);

        jLabel6.setText("Airline / City / Location:");

        jLabel7.setText("Nights (hotel only):");

        cancelBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cancelBtn.setText("âœ•  Cancel");
        cancelBtn.addActionListener(this::cancelBtnActionPerformed);

        saveBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        saveBtn.setText("âœ”  Save");
        saveBtn.addActionListener(this::saveBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(131, 131, 131)
                            .addComponent(cancelBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveBtn))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nightsSpinner)
                                .addComponent(dateSpinner)
                                .addComponent(typeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(titleField)
                                .addComponent(costField)
                                .addComponent(extraField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extraField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nightsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(saveBtn))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void extraFieldActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        String title   = titleField.getText().trim();
        String costTxt = costField.getText().trim();
        String extra   = extraField.getText().trim();
        String type    = (String) typeComboBox.getSelectedItem();

        if (title.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Title cannot be empty.");
            return;
        }
        if (costTxt.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Cost cannot be empty.");
            return;
        }
        if (extra.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please fill in Airline / City / Location.");
            return;
        }

        double cost;
        try {
            cost = Double.parseDouble(costTxt);
            if (cost < 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Cost must be a positive number.");
            return;
        }

        java.util.Date d = (java.util.Date)
            ((javax.swing.SpinnerDateModel) dateSpinner.getModel()).getValue();
        String date = new java.text.SimpleDateFormat("yyyy-MM-dd").format(d);

        if ("Flight".equals(type)) {
            createdItem = new tripplanner.model.Flight(
                title, date, cost, extra, "N/A");
        } else if ("Hotel".equals(type)) {
            int nights = (int) nightsSpinner.getValue();
            createdItem = new tripplanner.model.Hotel(
                title, date, cost, extra, nights);
        } else {
            createdItem = new tripplanner.model.Activity(
                title, date, cost, extra);
        }

        dispose();
    }                                       

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        createdItem = null;
        dispose();
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                InputForm dialog = new InputForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField costField;
    private javax.swing.JSpinner dateSpinner;
    private javax.swing.JTextField extraField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSpinner nightsSpinner;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField titleField;
    private javax.swing.JComboBox<String> typeComboBox;
    // End of variables declaration                   
}
